services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --set redpanda.auto_create_topics_enabled=true
      - --kafka-addr=internal://0.0.0.0:9093,external://0.0.0.0:9092
      - --advertise-kafka-addr=internal://redpanda:9093,external://localhost:9092
    ports: ["9092:9092", "9644:9644"]
  console:
    image: redpandadata/console:latest
    environment:
      - KAFKA_BROKERS=redpanda:9093
    ports: ["8080:8080"]
    depends_on: [redpanda]
  schema-registry:
    image: apicurio/apicurio-registry-mem:2.6.0.Final
    ports: ["8081:8080"]
