global:
  scrape_interval: 15s

scrape_configs: 
  - job_name: "redpanda"
    static_configs: 
      - targets: ["redpanda:9644"]
        
  - job_name: "analytics-api" 
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:4000"]
        

  - job_name: "order-api" 
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3000"]